### PR TITLE
ofRoute: adds support for RegExp

### LINKED ISSUE #1: Feature request: wildcard
This would be very handy. Something with a "contains"-rule (e.g. `ofRoute('pizza*')`) or maybe a regex, too? 😄

### PR DESCRIPTION
**Pull request by JohannesHoppe**
fixes #1, also enhances readme a bit 

cheers! 🍻

### CODE REVIEW

**Comment by amcdnl** [comment]
awesome stuff! thanks

**Comment by JohannesHoppe** [comment]
image

**Comment by amcdnl** [comment]
Planning to update after work :)

**Comment by JohannesHoppe** [comment]
:wink:

**Comment by JohannesHoppe** [comment]
bump! :shipit:

**Pull request merged**
